version: '3.9'

services:
  postgres-dev:
    image: postgres
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=dtmoney_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
volumes:
  postgres-dev-data:
